教学视频：[YouTube - TensorFlow 2.0 Complete Course - Python Neural Networks for Beginners Tutorial](https://www.youtube.com/watch?v=tPYj3fFJGjk&list=LL&index=1&t=1898s)

## 工作原理

TensorFlow由两个组成部件构成:
- Graphs
- Sessions

Graph：TensorFlow的工作原理是创建一个计算图（a graph of defined computations），使用TensorFlow的本质就是创建一个计算图，当我们建立变量（Variable）的时候，变量就会被添加到图中去. 它只是一个定义的计算式，就如同写下一个方程，当我们没有确定变量（value）的时候，我们无法进行计算出确切值（evaluate），当 $v1+v2=v3$ 时，如果要计算 $v3$ 我们必须先获得 $v1,v2$ 的值.

Session：一种方式去执行graph的一部分或整个graph. 当我们开始一个session时，往往从图的最底层开始，因为它不依赖于其他变量，然后开始遍历整个图，开始计算graph的不同位置（这一点有点类似于拓扑排序）.

第一步，在collabratory中选择正确的TensorFlow版本

In [ ]:
%tensorflow_version 2.x  # 如果不在notebook中无需这句话

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.x  # 如果不在notebook中无需这句话`. This will be interpreted as: `2.x`.


TensorFlow 2.x selected.


In [ ]:
import tensorflow as tf  # 导入TensorFlow包
print(tf.version)  # 查看版本

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


## Tensor（张量）
tensor是一种对潜在高维空间中的向量或矩阵的泛化（a generalization of vectors and matrices to potentially higher dimensions）

这里的vector（向量）可以理解为一种数据点（data point），并且不是定义在某个特定的坐标系中的.

在TensorFlow中tensor就是一种**运算的定义**，最终会转化为value. 当我们创建graph的过程中，就是创建了一堆tensors（a graph of Tensor objects that details how tensors are related），它们表示了tensor之间的联系. 当我们执行一个session的时候，也就是执行graph的不同部分，本质上就是执行不同的tensors并且从中获得不同的结果.

tensor包含一个data type（tensor所存储的数据类型）和shape（tensor的形状）.

**data type**：float32, int32, string and others.

**shape**: Represents the dimension of data.

### 创建Tensors

下面给出了一些创造不同张量的例子，这几个tensor称为scalar value（标量值，仅表示一个值），与之对应的是vector value（向量值，表示多个值），创建方法为`tf.Variable(value, data_type)`.

In [ ]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.1415, tf.float64)
print(string)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>


### Rank/Degree of Tensors（tensor的阶数）
上面的代码所创建的就是0阶的tensor，就只有一个值.

当我们创建的tensor包含array或list，则至少为1阶；由最深的array或list的层数，决定一个tensor的阶数. 如下面两个例子：

In [ ]:
rank1_tensor = tf.Variable(['test', 'ok', 'time'], tf.string)  # 1阶，通常称为vector
rank2_tensor = tf.Variable([['test', 'ok', 'bye'], ['test', 'yes', 'hi']], tf.string)  # 2阶，通常称为matrix，必须为长方形序列才能成功创建
rank3_tensor = tf.Variable([[[0, 0], [0, 0]], [[1, 1], [1, 1]]], tf.int32)  # 两个2阶的matrices堆叠
rank3_tensor1 = tf.Variable([[[0, 0], [0, 0]], [[1, 1], [1, 1]], [[2, 2], [2, 2]]], tf.int32)  # 三个２阶matrices堆叠
rank3_tensor2 = tf.Variable([[[0], [0]], [[1], [1]], [[2], [2]]], tf.int32)  # 三个2x1的matrices堆叠
rank4_tensor = tf.Variable([[[[0], [0]], [[1], [1]], [[2], [2]]], [[[0], [0]], [[1], [1]], [[2], [2]]]], tf.int32)  # 同理4阶或更高阶的tensor

判断一个tensor的阶数方法：

In [ ]:
tf.rank(rank2_tensor)  # numpy=阶数

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### Shape of Tensors（tensor的形状）
shape告诉我们每一个维数上的元素的个数, rank3_tensor2.shape=(3, 2, 1)因为它是由3层2x1的matrices堆叠而成的.

In [ ]:
print(rank2_tensor.shape)

(2, 3)


### 改变Shape
相同的元素可以有不同的shape进行排列，可以使用`reshape()`函数方便的转换tensor的shape, reshape后的形状必须满足之前的总元素个数（不然咋顺着重排）.

In [ ]:
tensor1 = tf.ones([1, 2, 3])  # 定义一个shape=[3, 2, 1]的由1充满的tensor
tensor2 = tf.reshape(tensor1, [2, 3, 1])  # reshape原有元素到shape=[2, 3, 1]
tensor3 = tf.reshape(tensor2, [2, -1])  # 给定前几个维度，自动计算补全最后一个维度，所以前几个维度必须整除全部元素个数
tensor4 = tf.reshape(tensor3, [1, 2, -1])
print(tensor1)
print(tensor2)
print(tensor3)
print(tensor4)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


### tensor的类型
以下给出几种常用的tensor类型：
- Variable
- Constant
- Placeholder
- SparseTensor

其中前两者使用较多，上述全部类型中**除了**Variable以外都是不变的（immuttable），即在执行运算过程中无法改变.

当我们有可能改变一个变量的时候，就是用Variable.

### Evaluating Tensor
Evaluate（评估）即计算出tensor的值，由于tensor表示graph中的计算式，需要将tensor放到graph中去，并计算出它的值.